components:
  schemas:
    ContentSpace:
      properties:
        availableLanguages:
          items:
            type: string
          type: array
        author:
          $ref: '../../headless-person/headless-person-impl/openapi.yaml/components/schemas/Person'
        description:
          type: string
        id:
          type: integer
        name:
          type: string
        self:
          type: string
      type: object
    ContentSpaceCollection:
      properties:
        collection:
          $ref: '#/components/schemas/ContentSpaceCollection'
        elements:
          items:
            $ref: '#/components/schemas/ContentSpace'
          type: array
        numberOfItems:
          format: int
          type: number
        pages:
          properties:
            first:
              $ref: '#/components/schemas/ContentSpaceCollection'
            last:
              $ref: '#/components/schemas/ContentSpaceCollection'
            next:
              $ref: '#/components/schemas/ContentSpaceCollection'
          type: object
        self:
          $ref: '#/components/schemas/ContentSpaceCollection'
        totalNumberOfItems:
          type: number
          format: int
      type: object
info:
  description: ''
  title: Title
  version: 1.0.0
paths:
  /content-space:
    get:
      parameters:
        - in: query
          name: page
          schema:
            type: number
            format: int
        - in: query
          name: per_page
          schema:
            type: number
            format: int
      responses:
        200:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ContentSpace'
          description: ''
  /content-space/{id}:
    get:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ContentSpaceCollection'
          description: ''
openapi: 3.0.1