components:
  schemas:
    Person:
      properties:
        familyName:
          type: string
        id:
          type: integer
        self:
          type: string
      type: object
info:
  description: ''
  title: Title
  version: 1.0.0
paths:
  /person:
    get:
      responses:
        200:
          content:
            '*/*': {}
          description: ''
  /person/{id}:
    get:
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        200:
          content:
            '*/*': {}
          description: ''
openapi: 3.0.1